### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by agardnerIT** [SuperAayush/KLT-Killercoda#11]
The install command fails. Probably because single code fences are used and killercoda is trying to concatenate both lines into a single command.

Try the three code-fence version:

```
# is just so it shows on GitHub markdown. Remove the hash.
#```
#command one
#command two
#```{{exec}}
```

**Comment by SuperAayush** [comment]
Hey @agardnerIT!!

The command are correctly being copied to the terminal on the single click but the issue I am facing after that is:

1. Not able to run `kubectl wait --for=condition=Available deployment/klc-controller-manager -n keptn-lifecycle-toolkit-system --timeout=120s`. I think the command is taking more time to execute than the alloted time.
 
![Error-1](https://user-images.githubusercontent.com/78820926/227773811-60da8691-2844-4597-a225-ff04e024ced7.jpg)

2. Due to some weird reason this `git clone https://github.com/keptn-sandbox/lifecycle-toolkit-examples.git` command is running on the terminal but unable to make the desired repo directory i.e `lifecycle-toolkit-examples`

![Error-2](https://user-images.githubusercontent.com/78820926/227773941-89032a30-d1cd-4f1d-8cb0-5995e65f90f2.jpg)

**Comment by agardnerIT** [comment]
what other errors do you see? Is cert manager installed first? Are the CRDs installed?

**Comment by SuperAayush** [comment]
> what other errors do you see? Is cert manager installed first? Are the CRDs installed?

![Error](https://user-images.githubusercontent.com/78820926/227777003-158aa025-5ba2-4d96-ae5f-4f03ea5adda2.jpg)

I get this output from `kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml`:
![Error](https://user-images.githubusercontent.com/78820926/227777044-68cd7b52-9b9f-40f6-9531-0180f3bd44fb.jpg)

Can you have a look at the bottom of the screenshot:
`resource mapping not found for name: "klc-serving-cert" namespace: "keptn-lifecycle-toolkit-system" from "https://github.com/keptn/lifecycle-toolkit/releases/download/v0.5.0/manifest.yaml": no matches for kind "Certificate" in version "cert-manager.io/v1"
ensure CRDs are installed first
resource mapping not found for name: "klc-selfsigned-issuer" namespace: "keptn-lifecycle-toolkit-system" from "https://github.com/keptn/lifecycle-toolkit/releases/download/v0.5.0/manifest.yaml": no matches for kind "Issuer" in version "cert-manager.io/v1"
ensure CRDs are installed first`

Not sure if they are installed completely.

**Comment by SuperAayush** [comment]
I was experiencing this behavior in the local system setup as well.

**Comment by agardnerIT** [comment]
The helm chart isn’t installing the crds. Raise an issue on klt GitHub and ask in slack for max visibility. I’ll investigate tomorrow.  ---- On Sun, 26 Mar 2023 22:59:50 +1000  Aayush ***@***.***> wrote ----  
I was experiencing this behavior in the local system setup as well.

**Comment by agardnerIT** [comment]
I suggest using the [newer helm-based install](https://lifecycle.keptn.sh/docs/getting-started/#install-version-070-and-above).

```
Initialising Kubernetes... done

controlplane $ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.1
controlplane $ helm repo add klt https://charts.lifecycle.keptn.sh
"klt" has been added to your repositories
controlplane $ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "klt" chart repository
Update Complete. ⎈Happy Helming!⎈
controlplane $ helm upgrade --install keptn klt/klt -n keptn-lifecycle-toolkit-system --create-namespace --wait
Release "keptn" does not exist. Installing it now.
NAME: keptn
LAST DEPLOYED: Sun Mar 26 23:58:02 2023
NAMESPACE: keptn-lifecycle-toolkit-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
controlplane $ kubectl get ns    
NAME                             STATUS   AGE
default                          Active   31d
keptn-lifecycle-toolkit-system   Active   64s
kube-node-lease                  Active   31d
kube-public                      Active   31d
kube-system                      Active   31d
local-path-storage               Active   31d
controlplane $ kubectl get pods -n keptn-lifecycle-toolkit-system
NAME                                              READY   STATUS    RESTARTS   AGE
keptn-klt-certificate-operator-7df8b6c495-zmbnk   1/1     Running   0          69s
keptn-klt-lifecycle-operator-54c75c6dcb-l6cqm     1/1     Running   0          69s
keptn-klt-metrics-operator-75db78b69f-c65mh       1/1     Running   0          69s
keptn-klt-scheduler-869f44f478-t7nx5              1/1     Running   0          69s
controlplane $ 
```

**Comment by SuperAayush** [comment]
@agardnerIT closing this issue as resloved.
