### ISSUE TITLE
Fix kubectl short md text

### ISSUE THREAD

**Issue by agardnerIT** [SuperAayush/KLT-Killercoda#21]
Markdown text of the `kubectl --short` is wrong because it has been copied from the gettings tarted page.

Killercoda cluster (currently) uses a `1.26` cluster.

May I suggest wording like:

```
kubectl --short should show a version greater than or equal to 1.24
```

Rather than specifying an exact version.

Wording things in this way means we don't need to stay constantly up-to-date with markdown changes when Killercoda updates the clster versions underneath us (we have no control over that).

**Comment by SuperAayush** [comment]
Hey @agardnerIT!!

Although I have already mentioned about the details but let me refine it more.
 
![res1](https://user-images.githubusercontent.com/78820926/230127529-12840c4b-2f5e-4fac-9d22-176b9a1a1fc6.jpg)

**Comment by SuperAayush** [comment]
@agardnerIT please have a look at the PR #25 and do let me know if the changes are not relevant.
